### ISSUE TITLE
Comment regarding translation

### ISSUE THREAD

**Issue by AquaBat** [ScarletStudy/DGS2-3DS-Release#7]
In Case 2, in the flavor text for the medicine cabinet, Susato says “You’re smarter than the average bear”. I haven’t seen the original text to compare nor could I translate it myself, but I can’t help but feel that the original likely did not include this reference to Yogi Bear’s catchphrase. Your translation team distances itself from the AAI2 translation team and contrasts by insisting on a fully direct translation, providing notes for those who don’t understand certain things. Because of this, I don’t understand how something like this could have been slipped in. I was wondering if there was an explanation you had for this in order to give context.

**Comment by wabberz** [comment]
Here's the original text:
> でも。成歩堂さまなら、寝ぼけて
カギも、サラリと開けてしまいそうです。

Like you said, no Yogi Bear reference. But... We never distanced ourselves from the AAI2 translation, in fact, some of our members worked on that, too. What we said is, that we cannot _americanize_ DGS the way the rest of the series has been. If you're playing DGS2 now, I assume you've already played DGS1 and you probably understand by now why that is.

Our translation is still a localization, as we do replace jokes and references nobody but a native Japanese audience would understand. We just didn't make the characters Americans or change the location to Los Angeles. I'm a bit surprised this is the first pop culture reference you found, since DGS1 also has its fair share. We still try to emulate the style of the offical localizations, after all.

If this really were a direct, unedited, literal translation, it would be incredibly bland and repetitive - and we would need many, many more notes than what we have right now.

So to answer your question - this didn't "slip in", it's in there on purpose.

**Comment by AquaBat** [comment]
In addition, I’d like to point out Souseki’s dialogue in the Gaol.
“Near! Far! Wherever YOU are, Substitute!”
In the translation notes, you referred to Souseki’s mannerisms as difficult to translate 1:1. However, despite them being rather awkward, none of them have been references to something in pop culture, like this reference to the Titanic movie and its soundtrack.

I hope these are just isolated incidents.

**Comment by wabberz** [comment]
Refer to my original reply.

**Comment by AquaBat** [comment]
The reply popped up while I was typing that addendum, so I deleted what I typed up when I saw it. Sorry.

I don’t remember there being a discrepancy like this, and I don’t remember seeing anything like this in DGS1. But if that’s the case, I apologize for making assumptions.

**Comment by wabberz** [comment]
No worries.
